### ISSUE TITLE
Problem with wcbench  

### ISSUE THREAD

**Issue by stefanoperone** [dfarrell07/wcbench#57] opened 2015-02-24 08:36 UTC
Hi, I'm doing a lot of simulations with wcbench. I'm using Fedora20 because,with ubuntu I cannot connect to the Karaf's controller. Solved this problem, I'm running tests (in localhost), but when launching wcbench, with "./wcbench.sh -r" command or with "./loop_wcbench.sh -l" command, at the end of running in the results.csv file the elements of the "total ram" column and the "used ram" columns are nulls.
This is the result with "./stats.py -s flows ram" comand : 
{'flows': {'max': 21659,
           'mean': 7173.8737,
           'min': 2687,
           'relstddev': 68.084,
           'stddev': 4884.209}
'sample_size': 586,
'used_ram': {'max': 0,
              'mean': 0.0,
              'min': 0,
              'relstddev': 0.0,
              'stddev': 0.0}}

Maybe, this is the problem:
./stats.py -S
Traceback (most recent call last):
  File "./stats.py", line 345, in <module>
    stats_map[stat]()
  File "./stats.py", line 168, in compute_iowait_stats
    self.compute_generic_stats("iowait", self.iowait_col)
  File "./stats.py", line 249, in compute_generic_stats
    generic_stats["min"] = int(numpy.amin(stats_col))
  File "/usr/lib64/python2.7/site-packages/numpy/core/fromnumeric.py", line 2209, in amin
    out=out, keepdims=keepdims)
  File "/usr/lib64/python2.7/site-packages/numpy/core/_methods.py", line 21, in _amin
    out=out, keepdims=keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by dfarrell07** [comment] 2015-02-24 14:25
> I'm using Fedora20 because,

Are you using a [manual install](https://github.com/dfarrell07/wcbench#user-content-detailed-walkthrough-manual) or a the [project's Vagrant environment](https://github.com/dfarrell07/wcbench#user-content-detailed-walkthrough-vagrant)? I recommend the Vagrant environment if possible, for it's consistency and isolation.

> with "./wcbench.sh -r" command or with "./loop_wcbench.sh -l" command

I assume you started ODL using [WCBench's helper function](https://github.com/dfarrell07/wcbench/blob/master/wcbench.sh#L661-L702, via `wcbench -o`? If not, note that you'll need to [do the Karaf config](https://github.com/dfarrell07/wcbench/blob/master/wcbench.sh#L704-L761) manually.

> at the end of running in the results.csv file the elements of the "total ram" column and the "used ram" columns are nulls.

Can you include the contents of `results.csv`?

> Maybe, this is the problem:
./stats.py -S

If your `results.csv` file is ill-formed, as would be the case if you're missing those RAM columns, `stats.py` will fail. So that's not the issue, just a side-effect.

Generally, when debugging anything with WCBench, I suggest using the verbose (`-v`) flag. Try that and see if you get some useful output, perhaps error messages about RAM checks.

**Comment by dfarrell07** [comment] 2015-02-24 14:30
> "total ram" column and the "used ram" columns are nulls

Was the `free_ram` column **not** null then? That would be unexpected and interesting.

Note that for runs against ODL on the same host as WCBench, [these are the three commands issued to gather RAM info](https://github.com/dfarrell07/wcbench/blob/master/wcbench.sh#L61-L63). You may want to check them on your test system to see if they work as expected.

**Comment by stefanoperone** [comment] 2015-02-25 09:35
I used a manual install;
I started ODL using wcbench -o function, with this result:

./wcbench.sh -o
Starting OpenDaylight
Will repeatedly attempt connecting to Karaf shell until it's ready
Issued `dropAllPacketsRpc on` command via Karaf shell to localhost:8101
Issued `log:set ERROR` command via Karaf shell to localhost:8101

After, I used for example ./wcbench.sh -v -t 2 -r with this result:

./wcbench.sh -v -t 2 -r 
Set MS_PER_TEST to 120000, TESTS_PER_SWITCH to 1, CBENCH_WARMUP to 0
karaf: JAVA_HOME not set; results may vary
Running ...
Collecting pre-test stats
Running CBench against ODL on localhost:6633
cbench: controller benchmarking tool
   running in mode 'latency'
   connecting to controller at localhost:6633 
   faking 32 switches offset 1 :: 1 tests each; 120000 ms per test
   with 100000 unique source MACs per switch
   learning destination mac addresses before the test
   starting test with 0 ms delay after features_reply
   ignoring first 0 "warmup" and last 0 "cooldown" loops
   connection delay of 0ms per 1 switch(es)
   debugging info is off
Collecting post-test stats
Collecting time-irrelevant stats
Average responses/second: 26875.73

Shown below the screenshot of result.csv file; the problem is in Ram's coloumn.

![images1](https://cloud.githubusercontent.com/assets/11172791/6368064/69058972-bcd9-11e4-8743-8ea4dab9c3b7.png)
![images2](https://cloud.githubusercontent.com/assets/11172791/6368065/6905f952-bcd9-11e4-8d2e-4f74c6a1075a.png)

**Comment by dfarrell07** [comment] 2015-02-25 14:30
> Shown below the screenshot of result.csv file; the problem is in Ram coloumn.

Looking closer, actually all of the columns past `human_time` are wrong. The issue is that `human_time` on your system is resolving to a value that itself has commas, which is throwing off the CSV rows.

**Comment by dfarrell07** [comment] 2015-02-25 14:37
I raise #58 to track fixing the command such that it doesn't output commas, without regard for timezone.

**Comment by stefanoperone** [comment] 2015-02-25 15:10
Perfect, 
thank you very much, Daniel :)

**Comment by dfarrell07** [comment] 2015-02-25 15:41
@stefanoperone Can you try the fix I commited in 9455c121e724be950478515da657cbc20d1c1bb7?

Also, can you give me the outputs of `date` and `date +"%F %T %Y %Z"`, as an extra verification?

**Comment by stefanoperone** [comment] 2015-02-25 19:36
With this change:

results[$(name_to_index "end_time")]=`date +%s`
results[$(name_to_index "human_time")]=`date +"%F %T %Y %Z"`

I have this result:
![image](https://cloud.githubusercontent.com/assets/11172791/6378822/fead36e2-bd2d-11e4-9806-8e703a731126.jpg)

**Comment by dfarrell07** [comment] 2015-02-25 21:35
Perfect, looks fixed. :)

**Closed** 2015-02-25 21:35 UTC

**Comment by dfarrell07** [comment] 2015-02-25 21:38
@stefanoperone - Thanks for reporting this issue, btw. :+1:
